DROP TABLE IF EXISTS TB_COMMANDE ;
DROP TABLE IF EXISTS TB_ADRESSE ; 
DROP TABLE IF EXISTS TB_PERSONNE ;
 
CREATE TABLE TB_PERSONNE (id_personne INT NOT NULL IDENTITY PRIMARY KEY, nom VARCHAR(50), prenom VARCHAR(50)); 

CREATE TABLE TB_ADRESSE (id_adresse INT NOT NULL IDENTITY PRIMARY KEY, adresse VARCHAR(150), cp VARCHAR(5), ville VARCHAR(50), id_personne int FOREIGN KEY REFERENCES TB_PERSONNE(id_personne));

CREATE TABLE TB_COMMANDE (id_commande INT NOT NULL IDENTITY PRIMARY KEY, reference VARCHAR(10), id_adresse INT, id_client int FOREIGN KEY REFERENCES TB_PERSONNE(id_personne));